### ISSUE TITLE
Any progress with save files?

### ISSUE THREAD

**Issue by smx06** [charlyzard/PS4SaveDataDecryptingTools#1]
Hello, Thanks for your efforts.
Is there any progress with decrypting save files themselves (from /user/home/uid/savedata/) with the obtained key?

**Comment by smx06** [comment]
I mean is it possible to make a payload with a call to sceSblSsDecryptSealedKey&Co to decrypt the saves with one userID and then encrypt with another userID i.e. make save file transfer possible between accounts?

**Comment by smx06** [comment]
can help with tests/compiling/lite-coding/etc on 5.05 with mira/hen

**Comment by charlyzard** [comment]
You need to call sceFsLvdAttach first and then nmount with the decrypted key to mount the save data.

You can look in SceShellCore for how it's done.

**Comment by smx06** [comment]
Great! as I understand sceFsLvdAttach + nmount is for decrypting, and what about crypting it back? with another key (the key of another user, to be able to use this key on other user account)
Many thanks for hints

**Comment by charlyzard** [comment]
It's for mounting like in "mounting a partition" or "mounting an ISO image". You are asking the kernel "hey please mount this encrypted pfs image with this key, thank you ;-)"

**Comment by smx06** [comment]
Big Thanks/Gracias!
Can you plz tell me where to get this defines for 5.05? (i didn't find em anywhere):

#define KERN_PTRACE_CHECK_1 0xAC2F1
#define KERN_PTRACE_CHECK_2 0xAC6A2
#define KERN_SCE_SBL_SS_DECRYPT_SEALED_KEY 0x5FB800

As for other defines i understand this are actual for 5.05 instead of those defined in your .h:
// 5.05
//https://github.com/ExodusSecurity/PS4Offsets-With-Payloads/blob/master/README.md
#define KERN_XFAST_SYSCALL 0x1C0 //5.0x twitter.com/C0rpVultra/status/992789973966512133
#define KERN_PRISON_0		0x10986a0
#define KERN_ROOTVNODE	0x22c1a70
#define KERN_PMAP_PROTECT	0x2E3090
#define KERN_PROCESS_ASLR 0x194875
#define KERN_PTRACE_CHECK 0x30D9C3

#define KERN_PMAP_PROTECT	0x2E3090
#define KERN_PMAP_PROTECT_P	0x2E30D4
#define KERN_PMAP_STORE		0x22CB570
#define DT_HASH_SEGMENT		0xB5EF30

#define kern_off_printf                     0x436040
#define kern_off_copyin                     0x1EA710
#define kern_off_copyout                    0x1EA630
