### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by Radu13** [charlyzard/PS4SaveDataDecryptingTools#4]
Hello Charlyzard, you keep working on this open source save decryptor?
You have a social where you post update informarions?

**Comment by charlyzard** [comment]
I gave away my PS4 to my nephew, so no updates for the time being. The code is for 4.05. For 5.05 you can use [https://github.com/cfwprpht/libhb-master](https://github.com/cfwprpht/libhb-master) for decrypting the save key.
